version: '3.8'

services:

  nginx:
    image: nginx:1.19-alpine
    ports:
      - 80:80
    networks:
      - default
    volumes:
      - ./src/api:/var/www/api:ro,delegated
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - api

  api:
    container_name: api
    build: ./src/api
    working_dir: /var/www/api
    environment:
      MAIL_HOST: host.docker.internal
    volumes:
      - ./src/api:/var/www/api:delegated
    networks:
      - default
    depends_on:
      - mysql

  mysql:
    image: 'mysql:8.0'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'database'
      MYSQL_USER: 'username'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - dbdata:/var/lib/mysql:delegated
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    networks:
      - default
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]

networks:
  default:
    driver: bridge

volumes:
  dbdata:
    driver: local
