version: '3'

services:

  mysql:
    image: 'mysql:8.0'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'database'
      MYSQL_USER: 'username'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'dbdata:/var/lib/mysql'
    networks:
      - default
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'redisdata:/data'
    networks:
      - default
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

networks:
  default:
    driver: bridge

volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local
